version: 0.2

env:
  variables:
    PYTHON_VERSION: "3.11"

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "No build for PyScript"

  build:
    commands:
      - echo "Preparing Static Site"


artifacts:
  files:
    - '**/*'
